---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: <CLUSERNAME>
  namespace: <VSPHERE NAMESPACE>
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["100.64.0.0/13"]
    pods:
      cidrBlocks: ["100.96.0.0/11"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.24.9+vmware.1-tkg.4  # TKr Version
    controlPlane:
      replicas: <REPLICAS>
    workers:
      machineDeployments:
        - class: node-pool
          name: <WORKPER POOL NAME>
          replicas: <REPLICAS>
    variables:
      - name: vmClass
        value: <VM CLASS>
      - name: storageClass
        value: <STORAGE CLASS> 
      - name: defaultStorageClass
        value: <STORAGE CLASS>
      - name: trust
        value:
          additionalTrustedCAs:
          - name: <INTERNAL_CA_NAME>  # ONLY when it differs from TkgServiceConfiguration resource, must match name in additional CA secret CLUSTER-NAME-user-trusted-ca-secret

