apiVersion: v1
kind: Namespace
metadata:
  name: kuard

---
apiVersion: v1
kind: Service
metadata:
  namespace: kuard
  name: kuard-service
spec:
  type: ClusterIP
  selector:
    run: kuard
  ports:
  - name: kuard-http
    protocol: TCP
    port: 8080
    targetPort: http-web

---
apiVersion: v1
kind: Pod
metadata:
  namespace: kuard
  labels:
    run: kuard
  name: kuard
spec:
  containers:
  # Default image: gcr.io/kuar-demo/kuard-amd64:blue
  - image: <PRIVATE_REGISTRY>/library/kuar-demo/kuard-amd64:blue
    name: kuard
    ports:
    - containerPort: 8080
      name: http-web

