---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <ROLEBINDING-RESSOURCE-NAME>
  namespace: <KUBERNETES-NAMESPACE>
roleRef:
  kind: Role
  name: <ROLE-NAME>                      # Reference to the Role defined in dev-role-sso.yaml
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:<USERNAME>@<DOMAIN>          
  apiGroup: rbac.authorization.k8s.io