apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard
  namespace: tkg-system
spec:
  fetch:
    imgpkgBundle:
      # Default Registry: projects.registry.vmware.com/tkg/packages/standard/repo:v2.1.0
      image: <PRIVATE_REGISTRY>/tkg/packages/standard/repo:v2.2.0
