---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <ROLE-NAME>
  namespace: <KUBERNETES-NAMESPACE>
rules:
- apiGroups:
  - '*'
  resources:
  - 'pv'
  - 'pvc'
  verbs:
  - get
  - list
  - create
